apiVersion: apps/v1
kind: Deployment
metadata:
  name: notas-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notas-api
  template:
    metadata:
      labels:
        app: notas-api
    spec:
      containers:
      - name: notas-api
        image: notas-api:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
